name: Publish NuGet Packages

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'Directory.Build.props'
  workflow_dispatch:  # 手動実行を許可

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet build -c Release --no-restore

    - name: Pack NuGet packages
      run: dotnet pack -c Release --no-build --output ./nupkgs

    - name: Publish to GitHub Packages
      shell: pwsh
      run: |
        dotnet nuget add source --username KANAMORI-SYSTEM-Inc --password ${{ secrets.NUGET_PUBLISH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/KANAMORI-SYSTEM-Inc/index.json"
        Get-ChildItem ./nupkgs/*.nupkg | ForEach-Object {
          dotnet nuget push $_.FullName --source "github" --api-key ${{ secrets.NUGET_PUBLISH_TOKEN }} --skip-duplicate
        }
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_PUBLISH_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./nupkgs/*.nupkg
